name: CI

on:
  push:
    branches:
      - development
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  CI:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}
      - name: Use the previous version
        run: |
          echo ${{ steps.version.outputs.previous-version }}
      - run: git -v
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: shimataro/ssh-key-action@v2
        with:
         key: ${{ secrets.SSH_KEY }}
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Install
        run: npm ci --legacy-peer-deps
      - name: Build
        run: npm run build
