name: CI

on:
  push:
    branches:
      - development
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  CI:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [16]
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install
        run: npm ci --legacy-peer-deps
        shell: bash 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build
        run: npm run build