name: CI

on:
  push:
    branches:
      - development
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  CI:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [16]
    steps:
      - uses: actions/checkout@v2
        with:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install
        run: npm ci --legacy-peer-deps
      - name: Build
        run: npm run build