name: CI

on:
  push:
    branches:
      - development
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  CI:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
          node-version: '16'
      - name: Install
        run: git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/" && npm ci --legacy-peer-deps
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/" && npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        

