name: CI

on:
  push:
    branches:
      - development
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  CI:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [16]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.ACCESS_TOKEN}}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          token: ${{secrets.ACCESS_TOKEN}}
      - name: Install
        run: npm ci --legacy-peer-deps
      - name: Build
        run: npm run build
        with:
          token: ${{secrets.ACCESS_TOKEN}}